version: "0.1"
addresses:
  address@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
accessories:
  - name: address@mailscript.com
    type: mailscript-email
    address: address@mailscript.com
    key: owner
workflows:
  - name: Build failed to discord#channel
    trigger:
      accessory: address@mailscript.com
      config:
        criterias:
          - from: notifications@github.com
            subjectContains: run failed
    actions:
      - config:
          type: webhook
          body: |
            {
              "content": "Build failed: {{msg.subject}}"
            }
          url: "https://discord.webhook"
          opts:
            headers:
              Content-Type: application/json
            method: POST
